#!/usr/bin/env bash

## DOWNLOAD from JOSEPHS WEBSITE (SLOWER DOWNLOAD)                                 
#wget https://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
#wget https://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
#wget https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar    
                                                              
## OR DOWNLOAD FROM HERE (FASTER DOWNLOAD)                                          
# VOC2007 DATASET                                                              
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar 

# # VOC2012 DATASET                                                              
wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar

# Extract tar files
tar xf VOCtrainval_11-May-2012.tar
tar xf VOCtrainval_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar

# # Run python file to clean data from xml files
python gen_labels.py

# Get train by using train+val from 2007 and 2012
# Then we only test on 2007 test set
# Unclear from paper what they actually just as a dev set
cat train.txt val.txt > trainval.txt

mkdir ./images/ ./labels/

mv VOCdevkit/VOC2007/JPEGImages/*.jpg ./images/                                      
mv VOCdevkit/VOC2012/JPEGImages/*.jpg ./images/                                      
mv VOCdevkit/VOC2007/labels/*.txt ./labels/                                         
mv VOCdevkit/VOC2012/labels/*.txt ./labels/

# # We don't need VOCdevkit folder anymore, can remove
# # in order to save some space 
rm -rf VOCdevkit/

